---

- name: NODE EXPORTER | CHECK | Checking if Node Exporter is installed
  ansible.builtin.stat:
    path: "{{ node_exporter_install_path }}"
  register: node_exporter_binary

- name: NODE EXPORTER | CHECK | Checking version Node Exporter
  when: node_exporter_binary.stat.exists == true
  ansible.builtin.shell: "{{ node_exporter_get_version_cmd }}"
  register: node_exporter_check_version

- name: NODE EXPORTER | CHECK | Node Exporter get version regex
  ansible.builtin.set_fact:
    node_exporter_current_version: "{{ node_exporter_check_version.stdout_lines[0] | regex_replace('node_exporter, version ([0-9.]+).*$', '\\1') }}"
  when: node_exporter_binary.stat.exists == true

- name: NODE EXPORTER | CHECK | Checking upgrade version Node Exporter
  ansible.builtin.set_fact:
    node_exporter_version_greater: "{{ node_exporter_version > node_exporter_current_version }}"
  when: node_exporter_binary.stat.exists == true
