---

- name: NODE EXPORTER | Check
  ansible.builtin.include_tasks: check.yaml
  tags:
    - node_exporter

- name: NODE EXPORTER | Install
  when: node_exporter_binary.stat.exists == false or node_exporter_version_greater == true
  ansible.builtin.include_tasks: node_exporter.yaml
  tags:
    - node_exporter

- name: NODE EXPORTER | Configuration
  when: node_exporter_binary.stat.exists == false or node_exporter_version_greater == true
  ansible.builtin.include_tasks: configuration.yaml
  tags:
    - node_exporter